app: "mikudos-service-ts"
consumer_group: "mikudos-service-ts"
brokers:
  - "127.0.0.1:9092"
mongodb: "mongodb://omManager:managerpwd@dds-2ze1e3965fa544d4-pub.mongodb.rds.aliyuncs.com:3717/puzzle"
port: 50051
